# Generated by Django 4.2.7 on 2026-01-28 15:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('hazard_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Класс опасности')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип груза',
                'verbose_name_plural': 'Типы грузов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClimateCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Климатическое условие',
                'verbose_name_plural': 'Климатические условия',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Фирма',
                'verbose_name_plural': 'Фирмы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracks_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество путей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Конфигурация станции',
                'verbose_name_plural': 'Конфигурация станции',
            },
        ),
        migrations.CreateModel(
            name='WagonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип вагона',
                'verbose_name_plural': 'Типы вагонов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Wagon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wagon_number', models.CharField(max_length=50, unique=True, verbose_name='Номер вагона')),
                ('path_number', models.IntegerField(verbose_name='Номер пути')),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Позиция на пути')),
                ('length', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Длина (м)')),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Высота (м)')),
                ('max_load_weight', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Максимальный вес груза (т)')),
                ('arrived_at', models.DateTimeField(verbose_name='Дата и время прибытия')),
                ('condition_status', models.CharField(choices=[('OK', 'Исправен'), ('MINOR', 'Незначительные неисправности'), ('MAJOR', 'Значительные неисправности'), ('OUT_OF_SERVICE', 'Не пригоден к эксплуатации')], default='OK', max_length=20, verbose_name='Техническое состояние')),
                ('is_operational', models.BooleanField(default=True, verbose_name='Готов к эксплуатации')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('cargo_types', models.ManyToManyField(to='wagons.cargotype', verbose_name='Типы грузов')),
                ('climate_conditions', models.ManyToManyField(blank=True, to='wagons.climatecondition', verbose_name='Климатические условия')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wagons.firm', verbose_name='Фирма')),
                ('wagon_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wagons.wagontype', verbose_name='Тип вагона')),
            ],
            options={
                'verbose_name': 'Вагон',
                'verbose_name_plural': 'Вагоны',
                'ordering': ['path_number', 'position'],
            },
        ),
    ]
