# Generated by Django 4.2.7 on 2026-02-04 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagons', '0003_add_cistern_conductor_remove_climate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClimateCondition',
        ),
        migrations.AlterField(
            model_name='wagon',
            name='load_capacity',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Грузоподъёмность (т)'),
        ),
    ]
